import type { Metadata } from "next"
import "./globals.css"
import { ErrorProvider } from "@/context/ErrorContext"
import { AppModeProvider } from "@/context/AppModeContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <AppModeProvider>
          <ErrorProvider>{children}</ErrorProvider>
        </AppModeProvider>
      </body>
    </html>
  )
}
